version: '3'
services:
  xxl_job_db:
    image: registry.cn-hangzhou.aliyuncs.com/dockerhub_mirror/mysql-server:8.0.32
    restart: always
    container_name: xxl_job_db
    ports:
      - 33306:3306
    volumes:
      - "./init:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root_pwd

  xxl-job-admin:
    image: registry.cn-hangzhou.aliyuncs.com/dockerhub_mirror/xxl-job-admin:2.4.1
    restart: always
    ports:
      - 38080:8080
    environment:
      PARAMS: "--spring.datasource.url=jdbc:mysql://xxl_job_db:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai"
    depends_on: 
      - xxl_job_db