version: '3'
services:
  mysql:
    image: mysql/mysql-server:8.0.31
    restart: always
    hostname: mysql
    container_name: xxl_job_db
    ports:
      - 33306:3306
    volumes:
      - "./init:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: xxl-job
      MYSQL_ROOT_PASSWORD: 123456 #root管理员用户密码
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    networks:
      - xxl_job_net

  admin:
    image: xuxueli/xxl-job-admin:2.4.0
    restart: always
    hostname: admin
    container_name: xxl_job
    ports:
      - 38080:8080
    links:
      - mysql
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/xxl-job?Unicode=true&characterEncoding=UTF-8&autoReconnect=true
      - spring.datasource.password=123456
    depends_on: 
      - mysql
    networks:
      - xxl_job_net
networks:
   xxl_job_net:
    driver: bridge
